FROM php:7.4-fpm-alpine

LABEL maintainer="pierre@piwik.org"

COPY php.ini /usr/local/etc/php/conf.d/php-tester.ini

# https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
#RUN set -ex; \
#	curl -fsSL -o GeoIPCity.tar.gz \
#		"https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz"; \
#	curl -fsSL -o GeoIPCity.tar.gz.md5 \
#		"https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz.md5"; \
#	echo "$(cat GeoIPCity.tar.gz.md5)  GeoIPCity.tar.gz" | md5sum -c -; \
#	mkdir /usr/src/GeoIPCity; \
#	tar -xf GeoIPCity.tar.gz -C /usr/src/GeoIPCity --strip-components=1; \
#	mv /usr/src/GeoIPCity/GeoLite2-City.mmdb /usr/src/matomo/misc/GeoLite2-City.mmdb; \
#	rm -rf GeoIPCity*

COPY docker-entrypoint.sh /entrypoint.sh

# WORKDIR is /var/www/html (inherited via "FROM php")
# "/entrypoint.sh" will populate it at container startup from /usr/src/matomo
VOLUME /var/www/html

ADD ./html/adminer.php /home/
ADD activate_adminer.sh /usr/local/bin/
ADD delete_adminer.sh /usr/local/bin/
RUN chmod 775 /usr/local/bin/activate_adminer.sh
RUN chmod 775 /usr/local/bin/delete_adminer.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php-fpm"]
