FROM php:7.4-fpm-alpine

LABEL maintainer="pierre@piwik.org"

COPY php.ini /usr/local/etc/php/conf.d/php-tester.ini

# WORKDIR is /var/www/html (inherited via "FROM php")
# "/entrypoint.sh" will populate it at container startup from /usr/src/matomo
VOLUME /var/www/html

ADD ./html/adminer.php /home/
ADD activate_adminer.sh /usr/local/bin/
ADD delete_adminer.sh /usr/local/bin/
RUN chmod 775 /usr/local/bin/activate_adminer.sh
RUN chmod 775 /usr/local/bin/delete_adminer.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php-fpm"]
